const config = require('../config');
const { cmd, commands } = require('../command');
const os = require('os');
const { runtime } = require('../lib/functions');

// Register the 'alive' command
cmd({
    pattern: "alive",
    desc: "Check if the bot is online and show system info.",
    category: "main",
    filename: __filename
}, async (conn, mek, m, {
    from, quoted, body, isCmd, command, args, q, isGroup,
    sender, senderNumber, botNumber2, botNumber, pushname, isMe,
    isOwner, groupMetadata, groupName, participants, groupAdmins,
    isBotAdmins, isAdmins, reply
}) => {
    try {
        // Construct the system status message
        let status = `👹️ *_Chuti_Yakshani-Md_* 👹️
        
*Uptime:* ${runtime(process.uptime())}
        
*Ram usage:* ${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)}MB / ${Math.round(os.totalmem() / 1024 / 1024)}MB

*HostName:* ${os.hostname()}

*Owner:* *Dilla* *Editz*

♻️ *~Generated by Chuti_Yakshani-MD~* ♻️`;

        // Combine the system status with the alive message
        const aliveMessage = `${status}\n\n${config.ALIVE_MSG}`;

        // Send the combined message
        await conn.sendMessage(from, {
            image: { url: config.ALIVE_IMG },
            caption: aliveMessage
        }, { quoted: mek });
    } catch (e) {
        console.error(e);
        reply(`An error occurred: ${e.message}`);
    }
});
