const { cmd, commands } = require('../command');
const fg = require('api-dylux');
const getFbVideoInfo = require("fb-downloader-scrapper")

// Register the 'video' command
cmd({
    pattern: "fb",
    desc: "Download Fb videos",
    category: "download",
    filename: __filename
}, async (conn, mek, m, {
    from, quoted, body, isCmd, command, args, q, isGroup,
    sender, senderNumber, botNumber2, botNumber, pushname, isMe,
    isOwner, groupMetadata, groupName, participants, groupAdmins,
    isBotAdmins, isAdmins, reply
}) => {
    try {
        if (!q) return reply("Please provide the URL or the title.");

        // Search for the video on YouTube
        const search = await yts(q);
        const data = search.videos[0]; // Get the first search result
        const url = data.url;

        // Prepare the description with video details
        let desc = `
👹️ *_Chuti_Yakshani-MD Video Downloader_* 👹️

*Title :-* ${data.title}
*Description :-* ${data.description}
*Duration :-* ${data.timestamp}
*Uploaded :-* ${data.ago}
*Views :-* ${data.views}

♻️ *~Generated by Chuti_Yakshani-MD~* ♻️      
        `;

        // Send video details with thumbnail
        await conn.sendMessage(from, { image: { url: data.thumbnail }, caption: desc }, { quoted: mek });

        // Download the video
        let down = await fg.ytv(url);
        let downloadUrl = down.dl_url;

        // Send the video file
        await conn.sendMessage(from, { video: { url: downloadUrl }, mimetype: "video/mp4" }, { quoted: mek });
        
        // Send the video as a document file
        await conn.sendMessage(from, { document: { url: downloadUrl }, mimetype: "video/mp4", fileName: data.title + ".mp4", caption: "♻️ *~Generated by Chuti_Yakshani-MD~* ♻️" }, { quoted: mek });

    } catch (e) {
        console.log(e);
        reply(`${e}`);
    }
});
