const { cmd } = require('../command');
const TikTokAPI = require('tiktok-api');

// Initialize TikTok API
const tiktok = new TikTokAPI();

// Register the 'tiktok' command
cmd({
    pattern: "tk",
    desc: "Download TikTok videos",
    category: "download",
    filename: __filename
}, async (conn, mek, m, {
    from, quoted, body, isCmd, command, args, q, isGroup,
    sender, senderNumber, botNumber2, botNumber, pushname, isMe,
    isOwner, groupMetadata, groupName, participants, groupAdmins,
    isBotAdmins, isAdmins, reply
}) => {
    try {
        if (!q) return reply("Please provide the TikTok video URL.");

        // Extract video ID or URL from the input
        const url = q;

        // Download the TikTok video
        let video = await tiktok.video(url);

        // Send the video file
        await conn.sendMessage(from, { video: { url: video.url }, mimetype: "video/mp4" }, { quoted: mek });

        // Send the video as a document file
        await conn.sendMessage(from, { document: { url: video.url }, mimetype: "video/mp4", fileName: "video.mp4", caption: "♻️ *~Generated by Chuti_Yakshani-MD~* ♻️" }, { quoted: mek });

    } catch (e) {
        console.log(e);
        reply(`${e}`);
    }
});
